Configs
go-park-mail-ru/2019_1_5factorial-team pull request #10
Opened 2019-03-26 16:25 UTC by Smet1

2019-03-28 15:17 UTC, ksenobait09 requested changes

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/config_reader/configReader.go
> +	data, err := ioutil.ReadFile("configs/" + filename)
относительный путь - плохо

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/config_reader/configReader.go
> +	data, err := ioutil.ReadFile("configs/" + filename)
я расписывал лене почему в его pull requests

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/config_reader/configReader.go
> +	data, err := ioutil.ReadFile("configs/" + filename)
либо абсолютный путь (обычно конфиги лежат в папке /etc/*), либо передавать путь в аргументе к бинарнику

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/fileproc/consts.go
>  const UploadPath = "/var/www/media/factorial"
если это унесено в конфиг, нужно удалять отсюда тогда

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/fileproc/consts.go
>  const UploadPath = "/var/www/media/factorial"
и как ты решаешь проблему со значениями по умолчанию?

2019-03-28 15:17 UTC, ksenobait09 commented on configs/cookie_config.json
> +{
Не коммить конфиги в репу. В репе должны быть максимум - шаблоны для конфига. Иначе каждый будет коммитить изменения конфига в репу, ты спулишь мастер и работать у тебя не будет. Сами конфигурационные файлы должны быть в .gitignore( а еще лучше - вообще вне репозитория, /etc/*)

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/session/cookieConfig.go
> +	CookieConf.CookieTimeHours = time.Duration(CookieConf.CookieDuration * int64(time.Hour))
мне не нравится, что есть поле с названием CookieDuration, которое int64, а есть CookieTimeHours - которое time.Duration. 

И что делать если ты захочешь указывать не в часах?

Посмотри функцию https://golang.org/pkg/time/#ParseDuration

2019-03-28 15:17 UTC, ksenobait09 commented on internal/pkg/config_reader/configReader.go
> +package config_reader
лучше бы ты воспользовался каким-нибудь готовым решением, вроде viper, но это не обязательно.

2019-03-29 11:48 UTC, Smet1 commented on internal/pkg/config_reader/configReader.go
> +	data, err := ioutil.ReadFile("configs/" + filename)
done

2019-03-29 11:48 UTC, Smet1 commented on internal/pkg/fileproc/consts.go
>  const UploadPath = "/var/www/media/factorial"
done

2019-03-29 11:48 UTC, Smet1 commented on internal/pkg/session/cookieConfig.go
> +	CookieConf.CookieTimeHours = time.Duration(CookieConf.CookieDuration * int64(time.Hour))
done

2019-03-29 11:49 UTC, Smet1 commented on configs/cookie_config.json
> +{
мне к ним постфикс дописать .example?

2019-03-29 13:12 UTC, Smet1 commented on internal/pkg/user/database.go
> +				Score:        rand.Intn(250000),
эта хрень сделана нормально в ветке (user_mongo_db)

2019-03-30 00:04 UTC, ksenobait09 requested changes

2019-03-30 00:04 UTC, ksenobait09 commented on configs/cookie_config.json
> +{
.example, .template, как угодно

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/server/server.go
> +func GetInstance() *MyGorgeousServer {
хз зачем здесь эта функция

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/server/server.go
> +var instance *MyGorgeousServer
хз зачем здесь инстанс

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/server/server.go
> +	instance = mgs
ну и это  тоже мусор

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/config/config.go
> +func (sc *ServerConfig) New(configsDir string) *ServerConfig {
оч запутанная логика, создает конфиг, параллельно сохраняет инстанс. Сделай просто функцию на пакете: Init(configsDir string) err  - которая будет вычитывать инфу в instance (ну и возвращать ошибку, проверять и валиться нужно снаружи, не внутри через log.Fatal)

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/config/config.go
> +func GetInstance() *ServerConfig {
Выглядит конечно прикольно, но постоянно лапша вида:

config.GetInstance().someConfig.MySetting - выглядит не очень красиво.

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/config/config.go
> +func GetInstance() *ServerConfig {
переименуй хотя бы в Get()

2019-03-30 00:04 UTC, ksenobait09 commented on internal/app/config/config.go
> +func GetInstance() *ServerConfig {
тогда все использование пакета config у тебя будет в двух функциях:

config.Init(path) - инициализация конфига

config.Get().SomePackageConfig.SomeSetting

2019-03-30 00:04 UTC, ksenobait09 commented on cmd/server/main.go
> +	s := server.MyGorgeousServer{}
некрасиво. 

хочу вместо:

s := server.MyGorgeousServer{}
s.New(*port)

s:= server.New(*port)

2019-03-31 09:38 UTC, Smet1 commented on internal/app/server/server.go
> +func GetInstance() *MyGorgeousServer {
done

2019-03-31 09:38 UTC, Smet1 commented on internal/app/server/server.go
> +var instance *MyGorgeousServer
done

2019-03-31 09:38 UTC, Smet1 commented on internal/app/server/server.go
> +	instance = mgs
done

2019-03-31 09:40 UTC, Smet1 commented on internal/app/config/config.go
> +func (sc *ServerConfig) New(configsDir string) *ServerConfig {
done

2019-03-31 10:14 UTC, Smet1 commented on internal/app/config/config.go
> +func GetInstance() *ServerConfig {
done

2019-03-31 10:14 UTC, Smet1 commented on cmd/server/main.go
> +	s := server.MyGorgeousServer{}
done

2019-03-31 18:24 UTC, ksenobait09 requested changes

2019-03-31 18:24 UTC, ksenobait09 commented on cmd/server/main.go
> +	configPath := flag.String("config", "/etc/5factorial/", "dir with server configs")
Это можно вынести из main(даже нужно) :

var configPath = ....
var port  := ....

2019-03-31 18:24 UTC, ksenobait09 commented on internal/app/server/server.go
> +	mgs := MyGorgeousServer{}
func New(port string) *MyGorgeousServer {
    return &MyGorgeousServer{
        port: port
    }
}

2019-03-31 18:24 UTC, ksenobait09 commented on internal/app/config/config.go
> +	err := config_reader.ReadConfigFile(configsDir, "static_server_config.json", &instance.StaticServerConfig)
Чем больше у тебя файлов конфигов, тем больше будет такого однообразного кода, когда ты читаешь из файла отдельного файла. Стоит, наверное, все конфиги объединить в один файл(оставить их разбитыми на сущностями)

По сути у тебя просто будет 1 файл конфига.

И ты будешь делать вычитывать прям сразу в &instance все конфиги

2019-04-06 13:53 UTC, ksenobait09 approved these changes

2019-04-14 14:28 UTC, merged