User mongo db
go-park-mail-ru/2019_1_5factorial-team pull request #11
Opened 2019-03-27 22:00 UTC by Smet1

2019-03-28 15:38 UTC, ksenobait09 requested changes

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +const DefaultAvatarLink = "../../../img/default.jpg"
че за путь такой?

Почему выходит за пределы папки с картинками?

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +const DefaultAvatarLink = "../../../img/default.jpg"
нельзя использовать относительные пути в коде

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +		AvatarLink:   DefaultAvatarLink,
И думаю, это значение должно быть в конфиге

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +		Score:        0,
не обязательно указывать, по дефолту 0

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +	return User{
Зачем тебе две сущности, для пользователя, которые отличаются одним полем?

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +	Id           int64         `bson:"-"`
не понял, зачем тебе это поле?

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +	return User{
причем я даже не уверен, что это поле используется(databaseUser.ID)

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/AfakeUsers.go
> +package user
Пиздец грязно ты решил с названием файла. Ты вполне можешь вообще всю генерацию (с вычитываением конфига и принятием решения - создавать их или нет) Вынести в отдельную функцию. И вызывать ее в конце init() user.database.go. Тогда ты хотя бы не будешь зависить от названия.

Но все равно, пиздец грязно, мне не нравится

2019-03-28 15:38 UTC, ksenobait09 commented on internal/pkg/user/AfakeUsers.go
> +package user
логика в  init - отвратительно

2019-03-29 19:36 UTC, Smet1 commented on internal/pkg/user/database.go
> +const DefaultAvatarLink = "../../../img/default.jpg"
теперь пустая линка

2019-03-29 19:37 UTC, Smet1 commented on internal/pkg/user/database.go
> +		Score:        0,
ну новый юзер же должен быть с 0 счетом

2019-03-29 19:37 UTC, Smet1 commented on internal/pkg/user/AfakeUsers.go
> +package user
подправил, но там тоже вопросы

2019-03-29 20:04 UTC, Smet1 commented on internal/pkg/user/database.go
> +	Id           int64         `bson:"-"`
убрал

2019-03-29 20:04 UTC, Smet1 commented on internal/pkg/user/database.go
> +	return User{
убрал бд юзера, везде теперь только юзеры

2019-03-30 00:35 UTC, ksenobait09 requested changes

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	database.InitConnection()
не, app - это сервисы

2019-03-30 00:35 UTC, ksenobait09 commented on internal/pkg/database/database.go
> +func GetDBSesion() *mgo.Session {
я не знаю, откуда у тебя любовь писать Getterы, но По сути, от обычного поля, это бы не отличалось.

только вместо database.Session

Ты везде писать будешь database.GetDBSession()

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	database.InitConnection()
у тебя не одна база, а несколько. К тому, в зависимости от микросервиса, ты будешь коннектиться к разным БД(Пакет у тебя один, но в например, сервисе авторизации ты хочешь подоединится только к одной БД)

Нужна возможность указывать, к каким базам хочу установить коннекты в этом сервисе

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	if config.GetInstance().DBUserConfig.GenerateFakeUsers {
это вообще логика не отсюда, унеси ее в пакет User

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	if config.GetInstance().DBUserConfig.GenerateFakeUsers {
и почему все это в main функции, а не функции run - сервера

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	if config.GetInstance().DBUserConfig.GenerateFakeUsers {
сделай отдельный метод у сервера - init()

прямо в начале функции Run() делаешь: 
func (s * hisAmesomeServer) Run() {
    s.init() // инициализация коннектов, юзеров  и прочего дерьма
{

2019-03-30 00:35 UTC, ksenobait09 commented on cmd/server/main.go
> +	if config.GetInstance().DBUserConfig.GenerateFakeUsers {
инициализацию конфигов, подалуй, можно оставить в  функции main

2019-04-01 19:36 UTC, ksenobait09 commented on internal/app/server/server.go
> +	// хочу передавать в json'е имя функи для фейк генерации и здесь ее вызывать
передавать в json имя функи?
Звучит ужастно

2019-04-01 19:36 UTC, ksenobait09 commented on internal/app/server/server.go
> +	for _, conn := range config.Get().DBUserConfig {
conn - это connection, хули у коннекшна есть какое-то поле GenerateFakeUsers? это явно не относится к сущности коннект

2019-04-01 19:36 UTC, ksenobait09 commented on internal/app/server/server.go
> +		if conn.GenerateFakeUsers {
Генерацию перенести в пакет users

2019-04-07 11:05 UTC, merged