Oauth
go-park-mail-ru/2019_1_5factorial-team pull request #14
Opened 2019-04-02 13:40 UTC by MrOcumare

2019-04-02 21:21 UTC, Smet1 commented
меня мучают сомнения, откуда ты отчекаутился?

2019-04-02 21:56 UTC, Smet1 requested changes

2019-04-02 21:56 UTC, Smet1 commented on internal/app/server/server.go
> +	httpSwagger "github.com/swaggo/http-swagger"
зачем?

2019-04-02 21:56 UTC, Smet1 commented on internal/app/server/server.go
> +	router.HandleFunc("/api/login_yandex", controllers.LoginFromYandex).Methods("POST", "OPTIONS")
мб лучше сделать `/api/login/yandex`?

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	json.Unmarshal(contents, &gToken)
почему не используешь мою функу? ParseRequestIntoStruct
там есть обработка ошибок, которые ты почему-то игноришь

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	Tocken string `json:"token"`
серьезно, tocken?

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	log.Println(gToken.Tocken)
хочу нормальные логи

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	getUserInfo(gToken.Tocken, w)
насколько я вижу, getUserInfo что-то возвращает
это что-то где?

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	response, err := http.Get("https://www.googleapis.com/oauth2/v2/userinfo?access_token=" + token) // по токену принемаем данные
поправь коммент на русский
и лучше юзать fmt.Sprintf (хотя я сам не везде это делаю))))00)

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +func getUserInfo(token string, w http.ResponseWriter) ([]byte, error) {
почему не передавать туда всю структуру целиком?

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +		return nil, fmt.Errorf("failed getting user info: %s", err.Error())
errors.new

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	defer response.Body.Close()
по-моему лучше после contents,`err := ioutil.ReadAll(response.Body)`

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	defer response.Body.Close()
поставить

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	if response.StatusCode != 200 {
magic constant из стандартного пакета http

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +		ErrResponse(w, response.StatusCode, "invalid token")
почему у тебя функа отправляет результат юзеру, а не хэндлер, который ты вешаешь на конец
нелогично, мне не нра

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +		return nil, fmt.Errorf("failed reading response body: %s", err.Error())
опять пакет errors

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var gToken = new(GoogleToken)
чет новенькое
почему не `gToken := GoogleToken{}` ??

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
опять new

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	err1 := json.Unmarshal(contents, &googleemnail)
err1 ?
зачем

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +		ErrResponse(w, response.StatusCode, "cant Unmarshal googleEmail")
возвращай err.Error()
или сначала оберни, а потом верни, иначе не понятно где что упало

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
и `googleemnail` почему не camelCase

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +		cookie := session.CreateHttpCookie(randToken, expiration)
это должно быть в хэндлере

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	randToken, expiration, err := session.SetToken(u.Id)
копипаст с вложенного ифа
сделай проще

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	randToken, expiration, err := session.SetToken(u.Id)
и убери это отсюда

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +type VkLogin struct {
не совсем понял почему массив

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +func LoginFromVK(w http.ResponseWriter, r *http.Request) {
тут те же ошибки что и в `LoginFromGoogle `

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +		return nil, fmt.Errorf("failed getting user info: %s", err.Error())
где-то ты используешь `errResponse`, а тут такое
и вынеси это в хэндлер

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +	return contents, nil
впринципе претензии такие же, что и в гугле

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	Tocken string `json:"token"`
угу

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +type Response struct {
расскажи, почему здесь так?

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	req, _ := http.NewRequest("GET", "https://login.yandex.ru/info", nil)
ты реши, как ты запросы делаешь
так или так `response, err := http.Get("https://api.vk.com/method/users.get?fields=email,photo_50&access_token=" + token + "&v=5.52")`

2019-04-02 21:56 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +}
правь по аналогии
и убери лишние комменты

2019-04-02 22:14 UTC, MrOcumare commented on internal/app/server/server.go
> +	httpSwagger "github.com/swaggo/http-swagger"
это я вообще не трогал o_O

2019-04-02 22:15 UTC, MrOcumare commented on internal/app/server/server.go
> +	router.HandleFunc("/api/login_yandex", controllers.LoginFromYandex).Methods("POST", "OPTIONS")
вообще все равно... тогда и на фронте надо будет переделать(я б так же оставил)

2019-04-02 22:16 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	Tocken string `json:"token"`
Бывает

2019-04-02 22:17 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var gToken = new(GoogleToken)
это то же самое, вроде 
или есть какие то весомые аргументы?

2019-04-02 22:18 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	json.Unmarshal(contents, &gToken)
сделаю
про функу забыл

2019-04-02 22:21 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	getUserInfo(gToken.Tocken, w)
пофиксю

2019-04-02 22:25 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	if response.StatusCode != 200 {
не понял

2019-04-02 22:26 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
чем тебе new не нра ?

2019-04-02 22:27 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	err1 := json.Unmarshal(contents, &googleemnail)
виноват

2019-04-02 22:27 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var gToken = new(GoogleToken)
https://github.com/go-park-mail-ru/2019_1_5factorial-team/pull/14/files#diff-129e6ad5a287cdf309df84225e7e6f1eR44
вот тут сделано через {}
а так разницы нет

2019-04-02 22:27 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	if response.StatusCode != 200 {
http.StatusOK

2019-04-02 22:28 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerVk.go
> +type VkLogin struct {
забей там ебучий json прилетает

2019-04-02 22:30 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var gToken = new(GoogleToken)
прост это мне напоминает жаву, поэтому и не нра

2019-04-02 22:35 UTC, ksenobait09 requested changes

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var gToken = new(GoogleToken)
gToken := new(GoogleToken) или gToken := &GoogleToken{}

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	contents, _ := ioutil.ReadAll(r.Body)
игнорирование ошибки

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
Давайте возьмем за привычку объявлять указатели на структуру как 
googleemnail := &GoogleEmail{}

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	u, err := user.CreateUser(yandexemail.DefaultEmail, yandexemail.DefaultEmail, "***")
у тебя одинаковая логика отсюда и до конца функи для всех трех вариантов oauth.

Мне как раз не нравится, что у тебя вся логика в контроллере, сплошным блоком, еще и функции на 50-60 строк каждая.

Сделай пакеты:

internal/pkg/oauth - в него вынеси общую логику для всех трех ouath( логин, создание урезанного юзера, если мы логинимся в первый раз)

internal/pkg/oauth/google
internal/pkg/oauth/yandex
internal/pkg/oauth/vk - в Эти три соответсвенно логику для всех трех вариантов oauth

По хорошему в контроллере у тебя не должно быть бизнес-логики:
1) Считал данные, 
2) вызвал функу чтобы провалидировать(если нужно)
3) вызвал функу, реализующую всю бизнес логику
4) отдал ответ пользователю, в зависимости от результатов предыдущих пунктов

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	u, err := user.CreateUser(yandexemail.DefaultEmail, yandexemail.DefaultEmail, "***")
Еще, пароль три звездочки.Во-первых, нужно вынести в константу для всех способов авторизации. во-вторых - нужно сделать какой-то особый пароль(вероятнее всего пустой) и не логинить пользователя, если он такой пароль ввел. Вы ведь не хотите, чтобы любой дурак зашел пользователем просто вьебав "***"

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	u, err := user.CreateUser(yandexemail.DefaultEmail, yandexemail.DefaultEmail, "***")
ну и давай нормально, не через CreateUser проверяй, существует такой юзер, а через FindUser какой-нибудь сначала.

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	u, err := user.CreateUser(yandexemail.DefaultEmail, yandexemail.DefaultEmail, "***")
Ты же сейчас в случае любой ошибки(даже если база отвалилась) - сразу логинишь юзера(а ведь его может и не быть вовсе)

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	u, err := user.CreateUser(yandexemail.DefaultEmail, yandexemail.DefaultEmail, "***")
Ну и логин давай ставить не похожий на email, обрезай до \@

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerVk.go
> +	u, err := user.CreateUser((string)((id.Response)[0].ID), (string)((id.Response)[0].ID), "***")
у меня в вк id - это цифры. Не думаю, что валидно сохранять email пользователю в виде: 1231242352

2019-04-02 22:35 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerVk.go
> +	u, err := user.CreateUser((string)((id.Response)[0].ID), (string)((id.Response)[0].ID), "***")
ДА и логин цифрами - тоже хуйня

2019-04-03 22:49 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +	u, err := user.CreateUser((string)((id.Response)[0].ID), (string)((id.Response)[0].ID), "***")
UPD не работает

2019-04-03 22:49 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerVk.go
> +	u, err := user.CreateUser((string)((id.Response)[0].ID), (string)((id.Response)[0].ID), "***")
- делай через strconv
- нельзя сохранить имя юзера?

2019-04-04 14:26 UTC, MrOcumare commented on internal/app/server/server.go
> +	router.HandleFunc("/api/login_yandex", controllers.LoginFromYandex).Methods("POST", "OPTIONS")
/api/session/vk_login

2019-04-07 12:25 UTC, Smet1 requested changes

2019-04-07 12:25 UTC, Smet1 commented on internal/pkg/controllers/oauth.go
> +		ErrResponse(res, status, err.Error())
почему ошибки юзеру возвращаются здесь, а не в хэндлере?

2019-04-07 12:25 UTC, Smet1 commented on internal/pkg/user/database.go
> -
это переделано в ветке с базами
мог меня спросить перед тем как менять

2019-04-07 12:25 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +	OauthUser(res, req, "yandex")
перечитай коммент ника

2019-04-08 20:01 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
Есть такая вещь, как стиль кодирования, он должен быть одинаковым, чтобы код написанный разными людьми был максимально однородным, похожим. Чтобы любой мог зайти в твои функции и разобраться что, да как. 

Каждое такое отличие, что отличается от кода во всем проекте заставляет задуматься, остановиться, почему это использовано здесь, а не что-то иное. Да и глазу непривычно new(smth)

2019-04-08 20:26 UTC, MrOcumare commented on internal/pkg/controllers/oauthControllerGoogle.go
> +	var googleemnail = new(GoogleEmail)
Уяснил)

2019-04-08 21:08 UTC, ksenobait09 requested changes

2019-04-08 21:08 UTC, ksenobait09 commented on internal/app/server/server.go
> +	router.HandleFunc("/api/session/login_yandex", controllers.LoginFromYandex).Methods("POST", "OPTIONS")
слушай, у вас api по rest, "/api/session/yandex", "/api/session/vk", "/api/session/google" - достаточно понять, что они делают, а любые урлы из нескольких слов - это некрасиво. (можешь завернуть в "/api/session/oauth/yandex", если хочешь)

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/controllers/oauthControllerYandex.go
> +		log.Println("\t", errors.Wrap(err, "ParseRequestIntoStruct error"))
странные ошибки через "\t", у кирилла такие же в контроллере?

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +		return http.StatusBadRequest, errors.Wrap(err, "get api url with token "+string(token)+"and service "+string(service)), "", time.Time{}
ух ебат, давай  errors.Wrapf(err, "get api url with token %q and service %q", token , service)

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +	fmt.Println(uuid)
убери потом эти принты

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +	if err != nil {
Ты все еще создаешь юзера в случае ЛЮБОЙ ОШИБКИ из функции `user.GetUser(uuid)`, нужно проверять на конкретную ошибку, что юзер не найден и тогда создавать, во всех остальных случаях нужно возвращать ошибку

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +			return http.StatusBadRequest, errors.Wrap(err, "err in user data"), "", time.Time{}
зачем время возвращать? оно же вроде логируется в самом начале строчки логов

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/parseStringOauth.go
> +
лишний отступ

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/parseStringOauth.go
> +	return nickname
Выглядит жутко. Давай вместо:
```
	nickname := ""
	splitEmail := strings.Split(email, "")
	for i := 0; i < len(splitEmail); i++ {
		if splitEmail[i] == "@" {
			return nickname + ending
		}
		nickname = nickname + splitEmail[i]
	}
	return nickname
```
Сделаем так:
`return strings.Split(email, "@")[0] + ending`

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/parseStringOauth.go
> +	login := nameVk + " " + lastNameVk
login с пробелом? @Smet1  у вас можно логин с пробелом по середине?

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/utilsOauth.go
> +		vkEmail, vkLogin := GetVkData(strconv.Itoa((userInfo.Response)[0].ID), (userInfo.Response)[0].Name, (userInfo.Response)[0].LastName)
вынеси (userInfo.Response)[0] в отдельную переменную

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +	if response.StatusCode != 200 || err != nil {
if response.StatusCode != http.StatusOk || err != nil {

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/parseStringOauth.go
> +func GetNickname(email string, service string) string {
1) давай не прокидывать service, ending можно дописать при вызове функции GetNickname()
2) сделай ее приватной
3) назови getLoginFromEmail

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/parseStringOauth.go
> +func GetVkData(idVk string, nameVk string, lastNameVk string) (string, string) {
1) приватной
2) getEmailAndLoginFromVK

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/utilsOauth.go
> +type VkUser struct {
это что за юзер такой, если внутри в него массив Response?

давай так 
```
type VkUser {
		ID       int    `json:"id"`
		Name     string `json:"first_name"`
		LastName string `json:"last_name"`
	}

type VkResponse struct {
    users []VkUser `json:"response"`
}

```

2019-04-08 21:08 UTC, ksenobait09 commented on internal/pkg/oauth/oauth.go
> +const DefaultPassword = " "
Значит решили дефолтный паспорт пробел? Почему не пустая строка?

2019-04-10 10:33 UTC, Smet1 commented on internal/pkg/oauth/parseStringOauth.go
> +	login := nameVk + " " + lastNameVk
гыыы
у нас можно все, пока валидации нет
поджопник канеш

2019-04-10 10:35 UTC, Smet1 commented on internal/pkg/controllers/oauthControllerYandex.go
> +		log.Println("\t", errors.Wrap(err, "ParseRequestIntoStruct error"))
к 1 рк так и было, сейчас пока ветки `logs` нет в деве, можно так оставить

2019-04-11 10:31 UTC, MrOcumare commented on internal/pkg/oauth/oauth.go
> +			return http.StatusBadRequest, errors.Wrap(err, "err in user data"), "", time.Time{}
это же дефолтное значение, которое я возвращаю чтобы удовлетворять  
func OauthUser(token string, service string) (int, error, string, time.Time)
тк в в случае успеха я возвращаю 
randToken, expiration, err := session.SetToken(searchingUser.Id) в

2019-04-15 15:22 UTC, merged