Session mongo db
go-park-mail-ru/2019_1_5factorial-team pull request #15
Opened 2019-04-02 21:08 UTC by Smet1

2019-04-08 07:21 UTC, ksenobait09 requested changes

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/database/database.go
> +			session, err = mgo.Dial(fmt.Sprintf("%s://%s:%s", "mongodb", val.Hostname, val.MongoPort))
почему не использовать DialWithInfo, чем самому собирать урл? 
http://bazaar.launchpad.net/+branch/mgo/v2/view/head:/session.go#L327

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	dt := DatabaseToken{
`DatabaseToken` - расплывчатое название, не понял что это за сущность, пока не вгляделся внурь.

МБ `UserSession` или что-то вроде того?

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	col, err := database.GetCollection(collectionName)
```
	col, err := database.GetCollection(collectionName)
	if err != nil {
		return DatabaseToken{}, errors.Wrap(err, "collection not found")
	}

```

Код повторяется во всех методах, да и другой таблицы у тебя скорее всего не предвидится. Убери копипаст

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +		return "", time.Time{}, errors.Wrap(err, "error while adding new user")
"error while adding new user" - ??

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	if dt.CookieExpiredTime.Sub(time.Now()) < 10*time.Minute && dt.CookieExpiredTime.Sub(time.Now()) > 0 {
Выглядят эти две строки слишком длинно и громоздко, упрости

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	fmt.Println(dt.CookieExpiredTime.Sub(time.Now()))
`dt.CookieExpiredTime.Sub(time.Now())` - используешь постоянно, заведи уже метод на структуре dt

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	fmt.Println(dt.CookieExpiredTime.Sub(time.Now()))
Хотя лучше поле, у тебя в рамках запроса результат `dt.CookieExpiredTime.Sub(time.Now())` меняться не должен. Такое маловерятно, но все же

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	err = col.Find(bson.M{"token": token}).One(&dt)
И эта операция у тебя в нескольких методах копипаститься, вынеси

2019-04-08 07:21 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	err = col.Find(bson.M{"token": token}).One(&dt)
Сделай уже методы на структуре(или функции оперирующие со структурой), которые будут выполнять простейшие операции - Вставку, update, удаление, поиск по id.  А потом уже используй их в функах с бизнес логикой.

2019-04-08 10:02 UTC, Smet1 commented on internal/pkg/database/database.go
> +			session, err = mgo.Dial(fmt.Sprintf("%s://%s:%s", "mongodb", val.Hostname, val.MongoPort))
done

2019-04-08 10:04 UTC, Smet1 commented on internal/pkg/session/database.go
> +	dt := DatabaseToken{
done

2019-04-08 11:55 UTC, Smet1 commented on internal/pkg/session/database.go
> +	col, err := database.GetCollection(collectionName)
не могу придумать, как это переделать
Вся эта канитель переехала в sessionCRUD.go
вроде сильно глаза не мусолит

2019-04-08 11:55 UTC, Smet1 commented on internal/pkg/session/database.go
> +		return "", time.Time{}, errors.Wrap(err, "error while adding new user")
done

2019-04-08 11:56 UTC, Smet1 commented on internal/pkg/session/database.go
> +	if dt.CookieExpiredTime.Sub(time.Now()) < 10*time.Minute && dt.CookieExpiredTime.Sub(time.Now()) > 0 {
done

2019-04-08 11:56 UTC, Smet1 commented on internal/pkg/session/database.go
> +	fmt.Println(dt.CookieExpiredTime.Sub(time.Now()))
сделал функу на структуре

2019-04-08 11:56 UTC, Smet1 commented on internal/pkg/session/database.go
> +	err = col.Find(bson.M{"token": token}).One(&dt)
сделал CRUD на структуре

2019-04-08 18:04 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +	col, err := database.GetCollection(collectionName)
не ну используй camelcase для названий файлов, ну позязя,

2019-04-08 18:28 UTC, ksenobait09 requested changes

2019-04-08 18:28 UTC, ksenobait09 commented on internal/pkg/session/sessionCRUD.go
> +	// ошибки с отсутсвтем коллекции не может быть, тк проверено выше
А если добавиться новая ошибка в getCollisionSession? или вернется ошибка другого типа из соединения(типа EOF)? Нет, обязательно должна быть проверка на конкретную ошибку с коллизией, а потом на все остальное

2019-04-08 18:28 UTC, ksenobait09 commented on internal/pkg/session/sessionCRUD.go
> +func (us *UserSession) Insert() error {
1) Ты зачем-то в CRUD функцию примешал часть бизнес логики. Это нужно проверять выше по стеку( CRUD должен быть унарым и ответственным только за одно - вставку. Нужно делать так: проверил на наличие, если нет - Insert, если есть - Update)
2) вполне можно заюзать логику, что "_id"  сессии и "_id" у профиля одинаковые. Тогда можно будет использовать функции вроде mgo.UpstertID

2019-04-08 18:28 UTC, ksenobait09 commented on internal/pkg/session/sessionCRUD.go
> +func getCollisionSession(id string) (UserSession, error) {
GetSessionByUserId

2019-04-09 12:35 UTC, Smet1 commented on internal/pkg/session/sessionCRUD.go
> +func getCollisionSession(id string) (UserSession, error) {
done

2019-04-09 12:35 UTC, Smet1 commented on internal/pkg/session/sessionCRUD.go
> +func (us *UserSession) Insert() error {
поправил круд, но айди не переделал и не буду

2019-04-09 12:36 UTC, Smet1 commented on internal/pkg/session/sessionCRUD.go
> +	// ошибки с отсутсвтем коллекции не может быть, тк проверено выше
сделал, как ты говорил через upsert

2019-04-14 13:59 UTC, merged