Logs
go-park-mail-ru/2019_1_5factorial-team pull request #16
Opened 2019-04-07 12:39 UTC by Smet1

2019-04-08 07:37 UTC, ksenobait09 requested changes

2019-04-08 07:37 UTC, ksenobait09 commented on internal/app/config/config.go
> +	log "github.com/sirupsen/logrus"
Придется везде в новых файлах вот так переименовывать импорт. Почти уверен, кто-нибудь забудет и у вас в коде будут две записи: log.*** и logrus.****

2019-04-08 07:37 UTC, ksenobait09 commented on internal/app/server/server.go
> +	InitLogs()
Хм, я тут подумал.Логи и бд ты инитишь по всему проекту, но к сущности MyGorgeousServer - это не относится. Ты не сохраняешь их в объекте сервер, не используешь его. А происходит инит в конструкторе сервера О_О

Если можно InitLogs() и database.InitConnection() унести в main, я бы унес в main. Если нет,  то оставь пока тут

2019-04-08 07:37 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	ctxLogger := log.WithFields(log.Fields{
Сделай уже свой метод обертку.

Как вариант можно сделать так: 

Сделать свой пакет internal/pkg/utils/log (название не придется нигде менять у пакета, к нему всегда можно будет обращаться как log.****)

В свой пакет вынеси инициализацию логрус, В нем  Сделай импорт тех функций из logrus, которые ты будещь использовать без изменений.

Типо такого:
```
var (
	New         = errors.New
	Errorf      = errors.Errorf
	Wrap        = errors.Wrap
	Wrapf       = errors.Wrapf
	WithMessage = errors.WithMessage
	WithStack   = errors.WithStack
	Cause       = errors.Cause
)

```

И в этот пакет добавь свою обертку с withFields, которую ты постоянно вставляешь.

Как вариант, какое-то логирование можно вынести в middleware

2019-04-08 18:40 UTC, ksenobait09 requested changes

2019-04-08 18:40 UTC, ksenobait09 commented on internal/pkg/controllers/leaderboardController.go
> +	//log "github.com/sirupsen/logrus"
useless comment

2019-04-08 18:40 UTC, ksenobait09 commented on internal/pkg/utils/log/log.go
> +		"func":       funcName,
не обязательно funcName, если у тебя есть URL же? Можно избавиться от одного аргумента

2019-04-08 18:40 UTC, ksenobait09 commented on internal/pkg/controllers/uploadAvatar.go
> +	ctxLogger := log.LoggerWithoutAuth("UploadAvatar", req)
Хочу middleware, который:

1) Проверяет из контекста авторизован ли пользователь
2) В зависимости от авторизован ли,  создавать этот  LoggerWithoutAuth или LoggerWithAuth с помощью данных в контексте и req
3) сохраняет этот логгер в контексте
4) методы на контексте типа:

ctx.Info("==========="),  которые принтить в логгер, сохраненный в контексте

2019-04-09 12:34 UTC, Smet1 commented on internal/pkg/controllers/leaderboardController.go
> +	//log "github.com/sirupsen/logrus"
done

2019-04-09 12:35 UTC, Smet1 commented on internal/pkg/utils/log/log.go
> +		"func":       funcName,
done

2019-04-09 12:35 UTC, Smet1 commented on internal/pkg/controllers/uploadAvatar.go
> +	ctxLogger := log.LoggerWithoutAuth("UploadAvatar", req)
done через контекст

2019-04-14 12:58 UTC, merged