Registration
go-park-mail-ru/2019_1_5factorial-team pull request #2
Opened 2019-03-03 18:49 UTC by Smet1

2019-03-03 20:24 UTC, ksenobait09 requested changes

2019-03-03 20:24 UTC, ksenobait09 commented on cmd/server/main.go
> +package main
Ты отчекаутился от уже существующей ветки(hello wordl), а запрашиваешь мерж изменений в dev, в итоге тут перемешались изменения из обоих веток. Переделай на мерж в ветку, от которой ты отчекаутился, тогда будут видны только изменения твоей ветки

2019-03-03 20:24 UTC, ksenobait09 commented on internal/app/server/server.go
> +	// CORS middleware
"// TODO: CORS, panic and auth middleware'

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +		AddErrHeader(res, http.StatusInternalServerError)
согласись, что объединить функи AddErrHeader + AddErrBody и AddOkHeader + AddBody сэкономит довольно много строк в респонсах

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +		// json unmarshal error
useless comment, так как по идеологии гошки ошибки всегда проверяются непосредственно после вызова. Экономь строки и постарайся умещать функцию на экран

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +		// some errors with validation
also useless comment

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +		// bad request
useless comment

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +type SingUp struct {
SingUpRequest

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +type SignUpOkResp struct {
SignUpOkResponse, не стоит экономить на трех буквах

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/responses.go
> +type errorMessage struct {
по аналогии с SignUpResponse - сделай errorResponse

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +type SignUpOkResp struct {
а вообще -SignUpResponse.

У тебя же нет других SignUpResponse кроме как для ok ответа

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +		AddErrHeader(res, http.StatusInternalServerError)
и назвать их можно как-то более емко: 

responseWithError, for example

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +		fmt.Println("once do")
Насколько полезным будет логирование, если  появится еще одна безымянная once do в коде?

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +			AvatarType: "jpg",
зачем тебе AvatarType?

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/user.go
> +	rid := rand.Int()
сделай инкрементный id

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +	Password string
пароль должен хранится в виде хеша

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +type DatabaseUser struct {
не совсем понял, зачем ты разделил на  User и DatabaseUser

2019-03-03 20:24 UTC, ksenobait09 commented on internal/pkg/user/user.go
> +package user
Мой совет - при разработки таких независимых пакетов - пиши unit тесты и дебаж ими, а не руками. Это и быстрее и потом тесты пригодятся

2019-03-04 08:34 UTC, Smet1 commented on internal/pkg/user/database.go
> +type DatabaseUser struct {
DatabaseUser на данный момент имитирует БД, а User занимается валидацией вставляемых данных и самим инсертом

2019-03-04 08:35 UTC, Smet1 commented on internal/app/server/server.go
> +	// CORS middleware
а паник куда?

2019-03-04 16:12 UTC, Smet1 commented on cmd/server/main.go
> +package main
 Done

2019-03-04 16:13 UTC, Smet1 commented on internal/app/server/server.go
> +	// CORS middleware
Done

2019-03-04 16:13 UTC, Smet1 commented on internal/pkg/controllers/usersController.go
> +		AddErrHeader(res, http.StatusInternalServerError)
Done

2019-03-04 16:24 UTC, Smet1 commented on internal/pkg/controllers/usersController.go
> +		// json unmarshal error
done

2019-03-04 16:24 UTC, Smet1 commented on internal/pkg/controllers/usersController.go
> +		// some errors with validation
also useless done

2019-03-04 16:25 UTC, Smet1 commented on internal/pkg/controllers/usersController.go
> +		// bad request
useless done

2019-03-04 16:49 UTC, Smet1 commented on internal/pkg/controllers/responses.go
> +type errorMessage struct {
это именно тело ответа, а не сам респонс

2019-03-04 16:49 UTC, Smet1 commented on internal/pkg/user/database.go
> +		fmt.Println("once do")
done, поменял на другой лог

2019-03-04 16:53 UTC, Smet1 commented on internal/pkg/user/database.go
> +			AvatarType: "jpg",
убрал avatarType

2019-03-04 17:56 UTC, Smet1 commented on internal/pkg/user/database.go
> +	Password string
добавил хэширование с bcrypt

2019-03-04 18:01 UTC, Smet1 commented on internal/pkg/user/user.go
> +	rid := rand.Int()
done

2019-03-05 10:55 UTC, ksenobait09 commented on internal/pkg/controllers/responses.go
> +type errorMessage struct {
SignUpResponse - тоже тело ответа

2019-03-05 10:56 UTC, ksenobait09 requested changes

2019-03-05 10:56 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +func getNextId() int {
Простая переменная, проще и быстрее через atomic

2019-03-05 11:02 UTC, ksenobait09 requested changes

2019-03-05 11:02 UTC, ksenobait09 commented on internal/pkg/user/database.go
> +	for i, val := range users {
собсна, при чтении из мапки тоже нужны мьютексты

2019-03-05 11:02 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +	OkResponse(res, SignUpResponse{u.Id})
При инициализации структуры - явно указывай поля:
SignUpResponse{Id: u.Id}

Это позволит не разъебать код, код ты внесешь изменения в структуру

2019-03-05 11:02 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +	OkResponse(res, SignUpResponse{u.Id})
Это не единственное место

2019-03-05 15:09 UTC, ksenobait09 approved these changes

2019-03-05 15:21 UTC, merged