authorization
go-park-mail-ru/2019_1_5factorial-team pull request #3
Opened 2019-03-06 00:49 UTC by Smet1

2019-03-06 00:52 UTC, Smet1 commented
хз откуда полетели исправления по стилям, я ничего не делал
ಠ_ಠ

2019-03-06 13:00 UTC, ksenobait09 requested changes

2019-03-06 13:00 UTC, ksenobait09 commented on internal/app/server/auth.go
> +func cookieMiddleware(next http.Handler) http.Handler {
authMiddleware

2019-03-06 13:00 UTC, ksenobait09 commented on internal/app/server/auth.go
> +package server
перенести в internal/middleware

2019-03-06 13:00 UTC, ksenobait09 commented on internal/app/server/auth.go
> +			ctx = context.WithValue(ctx,"realId", -1)
почему "realId"?

2019-03-06 13:00 UTC, ksenobait09 commented on internal/app/server/auth.go
> +				http.Error(res, "cookie invalid", http.StatusTeapot)
у тебя middleware, почему middleware прерывает запрос если пользователь неавторизован?

у меня например проставлен  кука, у тебя перезагрузился сервер и сессия выпала из памяти.

я вызываю запрос для скорборда, который не требует авторизации, а ты меня посылаешь на хуй и не обрабатываешь запрос.

2019-03-06 13:00 UTC, ksenobait09 commented on internal/app/server/auth.go
> +				http.Error(res, "cookie invalid", http.StatusTeapot)
У тебя же есть запросы, которые не обязательно нуждаются в авторизации, нельзя их откидывать. поэтому просто прокидывай вниз в контроллеры факт того, авторизован пользователь или нет и там уже отклоняй запрос, если для апи-конца нужна авторизация, а ее нет

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	id := req.Context().Value("authorized").(bool)
переменная id - bool????
isAuthorised хотя бы

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	if err != nil {
и правда, что за дичь? зачем?

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	id := req.Context().Value("authorized").(bool)
id???

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	expiration := time.Now().Add(10 * time.Hour)
Пользователь, может поставить expiration своей куки в год-два и не логаутиться совсем. Ты не проверяешь истекание куки на сервере

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +		Name:    "token",
Параметры куки: имя, expire time, ты повторяешь (и будешь повторять, когда будешь сохранять время истекания на сервере), получается магические константы, их нужно вынести

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	currentSession.Expires = time.Now().AddDate(0, 0, -1)
currentSession.Expires = time.Unix(0, 0)

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	AvatarLink string `json:"avatar_link"`
нужна линка, убери коммент

2019-03-06 13:00 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +var tokens map[string]int64
не хранится expiration кук, не чистятся старые токены

2019-03-07 07:45 UTC, Smet1 commented on internal/app/server/auth.go
> +			ctx = context.WithValue(ctx,"realId", -1)
тип айди в внутри сервера

2019-03-07 07:48 UTC, Smet1 commented on internal/app/server/auth.go
> +				http.Error(res, "cookie invalid", http.StatusTeapot)
как раз когда у пользователя нет куки, сеттиться статус, что пользователь не залогинен.
А вот когда у него есть кука, которая невалидна, я ее отклоняю, и по идеи должен попросить пользователя залогиниться еще раз

2019-03-07 07:57 UTC, Smet1 commented on internal/pkg/controllers/sessionController.go
> +	if err != nil {
я ее оставил
не знаю, как по-другому сделать, но это теперь в SetToken находится

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +	err = session.DeleteToken(currentSession.Value)
Сначала нужно пытаться удалить сессию в базе, потом обнулить Куку. Чтобы не возникло ситуации, когда произошла ошибка,  выбрасываем error response, А Куку сбрасываем

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +	id := req.Context().Value("authorized").(bool)
Посему булева переменная называется Id?

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/controllers/usersController.go
> +
Копипаста из метода sign in

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/controllers/sessionController.go
> +		currentSession, err := req.Cookie("token")
Копипаста из sign out

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/middleware/auth.go
> +			ctx = context.WithValue(ctx, "token", "")
Зачем токен в контексте?

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/session/cookieConfig.go
> +const cookieTimeHours = 10
Можно сделать так: 
const (
a=2, 
C =3, 
)

2019-03-08 16:06 UTC, ksenobait09 commented on internal/pkg/session/database.go
> +		CookieIssuedTime:  now,
Похоже поле CookieIssuedTime не используется

2019-03-09 13:16 UTC, Smet1 commented on internal/pkg/controllers/sessionController.go
> +		currentSession, err := req.Cookie("token")
чет не понимаю, где там копипаста

2019-03-09 15:03 UTC, ksenobait09 approved these changes

2019-03-09 16:07 UTC, merged