Painc middleware
go-park-mail-ru/2019_1_5factorial-team pull request #9
Opened 2019-03-25 13:21 UTC by Smet1

2019-03-26 16:27 UTC, ksenobait09 requested changes

2019-03-26 16:27 UTC, ksenobait09 commented on Dockerfile
> +RUN mkdir /var/www/media/factorial
нельзя хранить файлы, данные(в том числе БД) в докере, необходимо прокидывать наружу, на хост машину

2019-03-26 16:27 UTC, ksenobait09 commented on Dockerfile
> +RUN mkdir /var/www/media/factorial
и в данном случае можно заменить 

RUN mkdir /var/www
RUN mkdir /var/www/media
RUN mkdir /var/www/media/factorial

на

RUN mkdir -p /var/www/media/factorial

2019-03-26 16:27 UTC, ksenobait09 commented on Dockerfile
> +RUN mkdir /var/www/media/factorial
но после прокидывания не уверен, что нужно будет уже создавать папку

2019-03-26 16:27 UTC, ksenobait09 commented on Dockerfile
> +RUN cd ~
зачем тут cd?

2019-03-26 16:27 UTC, ksenobait09 commented on internal/pkg/controllers/helloWorldController.go
> +	panic("kek")
не думаю, что такое нужно коммитить)

Можешь убрать этот конец в принципе

2019-03-26 16:28 UTC, Smet1 commented on internal/pkg/controllers/helloWorldController.go
> +	panic("kek")
этот конец кстати удобный, можно чекнуть работает бэк или нет

2019-03-28 13:02 UTC, ksenobait09 commented on internal/pkg/controllers/helloWorldController.go
> +	panic("kek")
окей, только потом сделай нормальный конец с мониторингом)

2019-03-28 13:02 UTC, ksenobait09 approved these changes

2019-03-28 13:02 UTC, merged